<a href="https://colab.research.google.com/github/Abdulla-asim/DeepLearning/blob/main/Notebooks/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. Pytorch Fundamentals

In [ ]:
import torch


In [ ]:
torch.__version__

'2.3.1+cu121'

In [ ]:
t = torch.tensor([[2]])
print(t)
t.item()

tensor([[2]])


2

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

### Converting a tensor to a scalar. (works only with a single valued tensor)

In [ ]:
scalar.item()

7

### Creating a Vector (1 dimensional tensor)

In [ ]:
vector = torch.tensor([2, 5])
vector

tensor([2, 5])

In [ ]:
# checking the dimension of the vector
vector.ndim

1

In [ ]:
# checking the shape of the vector
vector.shape

torch.Size([2])

### Creating a matrix


In [ ]:
MATRIX = torch.tensor([[9, 5],
                       [3, 4]])
MATRIX

tensor([[9, 5],
        [3, 4]])

In [ ]:
# checking the dimension of the matrix
MATRIX.ndim

2

In [ ]:
# shape of the matrix
MATRIX.shape

torch.Size([2, 2])

### Creating a Tensor

In [ ]:
TENSOR = torch.tensor([[[1, 3],
                        [2, 4],
                        [6, 3]]])
TENSOR

tensor([[[1, 3],
         [2, 4],
         [6, 3]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 2])

### Random Tensors

In [ ]:
# random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.7935, 0.3977, 0.7793, 0.4916],
         [0.6818, 0.1512, 0.6311, 0.9337],
         [0.3075, 0.1540, 0.8414, 0.1659]]),
 torch.float32)

### Zeros and Ones

In [ ]:
# tensor of all zeros
zeros = torch.zeros(3, 4)
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# tensor of all ones
ones = torch.ones(4, 3)
ones, ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

### Creating a Range and Tensors Like

In [ ]:
# use torch.arrange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10)

# create a range of values from 0 to 10
zero_to_ten  = torch.arange(0, 10)
zero_to_ten

<ipython-input-20-a65db40e13ce>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# creating a tensor of zeros similar to another tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0, 1.2, 4.3],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([2, 4, 5],
                               dtype = torch.float16)
float_16_tensor

tensor([2., 4., 5.], dtype=torch.float16)

### Getting Information from Tensors

In [ ]:
# create a tensor
some_tensor = torch.rand(3, 4)

# find details about it
print(some_tensor)
print(f"Shape of Tensor: {some_tensor.shape}")
print(f"Data Type of Tensor: {some_tensor.dtype}")
print(f"Device the Tensor is stored on: {some_tensor.device}")

tensor([[0.6575, 0.7580, 0.8768, 0.1565],
        [0.9476, 0.2586, 0.8262, 0.0024],
        [0.8923, 0.0540, 0.0704, 0.8195]])
Shape of Tensor: torch.Size([3, 4])
Data Type of Tensor: torch.float32
Device the Tensor is stored on: cpu


## Manipulating Tensors (Tensor Operations)
### Basic Operations

In [ ]:
# adding a number to a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# multiplying by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Tensors don't change until re-assigned
tensor

tensor([1, 2, 3])

In [ ]:
# Add and re-assign
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [ ]:
tensor =  tensor - 10
tensor

tensor([1, 2, 3])

In [ ]:
# can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# original tensor is still unchanged
tensor

tensor([1, 2, 3])

In [ ]:
# Corresponding elements multiplications
print (tensor , "*", tensor)
print ("Equals: ", tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:  tensor([1, 4, 9])


### Matrix Multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [ ]:
# Element wise multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# can also use "@" symbol but it isn't recommended
tensor @ tensor

tensor(14)

In [ ]:
%%timeit
# matrix multiplication by hand
# (avoid for loops at all costs, they're very computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

48.3 µs ± 13.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%%timeit
torch.matmul(tensor, tensor)

2.62 µs ± 79.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


### One of the most common errors in deep learning (shape errors)

In [ ]:
#shapes need to be right
tensor1 = torch.tensor([[1, 2],[3, 4], [5, 6]], dtype=torch.float32)

tensor2 = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype=torch.float32)

# this line wile give an error
#torch.matmul(tensor1, tensor2)

### Transpose

In [ ]:
print(tensor1, "\n")
print(tensor2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [ ]:
print(tensor1,"\n")
print(tensor2.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 

tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [ ]:
# Operation works when tensor2 is transposed
print(f"Original shapes: tensor1 =  {tensor1.shape}, tensor2 =  {tensor2.shape}\n")
print(f"New shapes: tensor1 = {tensor1.shape}, tensor2.T = {tensor2.T.shape}\n")
print("Output: \n")
output = torch.matmul(tensor1, tensor2.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor1 =  torch.Size([3, 2]), tensor2 =  torch.Size([3, 2])

New shapes: tensor1 = torch.Size([3, 2]), tensor2.T = torch.Size([2, 3])

Output: 

tensor([[ 5., 11., 17.],
        [11., 25., 39.],
        [17., 39., 61.]])

Output shape: torch.Size([3, 3])


In [ ]:
# torch.mm() is short for torch.matmul()
torch.mm(tensor1, tensor2.T)

tensor([[ 5., 11., 17.],
        [11., 25., 39.],
        [17., 39., 61.]])

In [ ]:
# since the linear layer starts with a random weights matrix, let's make it reproducible
torch.manual_seed(42)

# This uses matrix multiplication
linear = torch.nn.Linear(in_features = 2, # in_features = matches inner dimension of input
                         out_features = 1) # out_features = describes outer value

x = tensor1
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[1.5488],
        [3.8038],
        [6.0588]], grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 1])


### Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# aggregation
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # gives and error
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [ ]:
# alternative way
torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(0), tensor(90), tensor(45.), tensor(450))

### Positional min/max

In [ ]:
# create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Return index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")


Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Change tensor data type

In [ ]:
# create a tensor
tensor =  torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
torch_int8 = tensor.type(torch.int8)
torch_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [ ]:
# checking out the backward() and grad() function
x = torch.tensor([[1, 2], [1, 2.]], requires_grad=True)
out = x.pow(2).sum()
out.backward()
x.grad

tensor([[2., 4.],
        [2., 4.]])

### Reshaping, Stacking, Squeezing and Unsqueezing

In [ ]:
# create tensor
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# change view (keep the original data but change view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# changing z changes x (a view can change its original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# stack tensors on top of each other (try chaging dim to 0 or 1)
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Squeezing the tensor to remove the dimension that is 1 e.g: in (1, 7) , remove the dimension that is 1
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])
New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])


In [ ]:
print(f"Squeezed tensor: {x_squeezed}")
print(f"its shape: {x_squeezed.shape}")

# adding an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

Squeezed tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
its shape: torch.Size([7])
New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape : torch.Size([1, 7])


In [ ]:
# create a tensor with specific shape
x_original = torch.rand(224, 224, 3)

# permute the original tensor to rearrange the axis order
# changing the values in the permuted tensor will chanage the value in the origianl tensor
x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (Selecting data from tensors)

In [ ]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# lets index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second squera bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second squera bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# get all the values of the 0th dimension and the 0 index of the 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# get all the values of the 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# get all the values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# get index 0 of the 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

Indexing is a bit confusing, so keep practicing and visualize

### PyTorch tensors and NumPy

In [ ]:
import torch
import numpy as np


In [ ]:
array = np.arange(1., 8.)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
# converting numpy array to tensor and chaging its type
tensor = torch.from_numpy(array).type(torch.float32)
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [ ]:
# change the array but keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# change in the tensor does not affect the array
tensor += 1
tensor, array

(tensor([2., 3., 4., 5., 6., 7., 8.]), array([2., 3., 4., 5., 6., 7., 8.]))

### Reproducibility

In [ ]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2237, 0.6038, 0.9877, 0.9749],
        [0.5136, 0.4066, 0.9063, 0.4309],
        [0.3597, 0.3577, 0.1103, 0.5331]])

Tensor B:
tensor([[0.8798, 0.7714, 0.6359, 0.9160],
        [0.6542, 0.5869, 0.0789, 0.4114],
        [0.5598, 0.5119, 0.7392, 0.2740]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import random

In [ ]:
## set random seed
RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed eveytime a new rand() is called
# without this, tensor_D would be different to tensor_C
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
!nvidia-smi

Wed Aug 14 08:57:06 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count the number of devices
torch.cuda.device_count()

1

In [ ]:
# Check fot Apple Silicon GPU
import torch
torch.backends.mps.is_available()

False

In [ ]:
# set the device type
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [ ]:
if torch.cuda.is_available():
  device = "cuda"
elif torch.backends.mps.is_available():
  device = "mps"
else:
  device = "cpu"

In [ ]:
device

'cuda'

In [ ]:
import torch


In [ ]:
# create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

# moce tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU

In [ ]:
# if tensor is on gpu we cant transform it to NumPy like this
# tensor_on_gpu.numpy()
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')