<a href="https://colab.research.google.com/github/Abdulla-asim/DeepLearning/blob/main/Notebooks/00_PyTorch_Fundamentals_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

## 1. Create a random tensor with shape (7, 7)


In [ ]:
import torch
tensor = torch.rand(7, 7)
tensor

tensor([[0.3142, 0.9230, 0.8082, 0.1452, 0.8882, 0.3343, 0.3550],
        [0.8059, 0.1852, 0.5712, 0.9319, 0.7196, 0.0973, 0.3805],
        [0.3181, 0.7353, 0.9904, 0.9061, 0.1975, 0.6124, 0.5349],
        [0.9953, 0.5523, 0.5346, 0.8425, 0.2614, 0.9123, 0.7825],
        [0.1602, 0.3624, 0.1238, 0.3612, 0.6893, 0.1998, 0.0989],
        [0.9416, 0.4724, 0.5086, 0.7067, 0.9433, 0.3981, 0.9885],
        [0.6862, 0.3607, 0.1196, 0.3111, 0.6874, 0.0458, 0.8896]])

## 2. Perform a matrix multiplication on the tensor from 1 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
tensor_2 = torch.rand(1, 7)
torch.matmul(tensor, tensor_2.T)


tensor([[1.2690],
        [1.3414],
        [1.5353],
        [1.9510],
        [0.7622],
        [1.9930],
        [1.3287]])

## 3. Set the random seed to 0 and do 2 & 3 over again.

In [ ]:
SEED = 0
torch.manual_seed(SEED)

tensor_1 = torch.rand(7, 7)
tensor_2 = torch.rand(1, 7)

torch.matmul(tensor_1, tensor_2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

## 4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [ ]:
GPU_SEED = 1234
torch.cuda.manual_seed(GPU_SEED)

## 5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [ ]:
torch.manual_seed(1234)

device = "cuda" if torch.cuda.is_available() else "cpu"

tensor_1 = torch.rand(2, 3).to(device)
tensor_2 = torch.rand(2, 3).to(device)

print(f"Device: {device}\n")
print(f"Tensor 1: {tensor_1}\n")
print(f"Tensor 2: {tensor_2}")

Device: cpu

Tensor 1: tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]])

Tensor 2: tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])


## 6. Perform a matrix multiplication on the tensors you created in 5 (again, you may have to adjust the shapes of one of the tensors).

In [ ]:
tensor_3 = tensor_1 @ tensor_2.T
tensor_3

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

## 7. Find the maximum and minimum values of the output of 7.

In [ ]:
print(f"Max of tensor_3: {tensor_3.max()}\n")
print(f"Min of tensor_3: {torch.min(tensor_3)}")

Max of tensor_3: 0.5617256760597229

Min of tensor_3: 0.3647301495075226


## 7. Find the maximum and minimum index values of the output of .

In [ ]:
argmax = tensor_3.argmax()
argmin = tensor_3.argmin()

print(f"arg max: {argmax}\narg min: {argmin}")

arg max: 3
arg min: 0


## 9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.
The output should look like:

In [ ]:
torch.manual_seed(7)

random_tensor = torch.rand(1, 1, 1, 10)
print(random_tensor, random_tensor.shape, "\n")

squeezed_random_tensor = random_tensor.squeeze()
print(squeezed_random_tensor, squeezed_random_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10]) 

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
